import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Verify certificates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="https://school.profuturo.education/theme/image.php/profuturo_base/theme/1746625818/favicon" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="moodle, Verify certificates" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body id="page-admin-tool-certificate-index" className="format-site admin path-admin path-admin-tool path-admin-tool-certificate dir-ltr lang-en yui-skin-sam yui3-skin-sam school-profuturo-education pagelayout-base course-1 context-1 notloggedin">
        {children}
      </body>
    </html>
  );
}
